"""add_company_branding_fields

Revision ID: 03fcdcc14ed8
Revises: 60cd61a0ddd2
Create Date: 2025-12-23 14:31:05.174587+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03fcdcc14ed8'
down_revision = '60cd61a0ddd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('primary_color', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('secondary_color', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('theme_colors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'theme_colors')
    op.drop_column('companies', 'secondary_color')
    op.drop_column('companies', 'primary_color')
    # ### end Alembic commands ###

