"""implement_comprehensive_client_schema

Revision ID: 275b3fe61a60
Revises: 78101427ef8c
Create Date: 2025-12-18 18:57:34.071013+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '275b3fe61a60'
down_revision = '78101427ef8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_travel')
    op.add_column('client_automobile', sa.Column('vehicle_make', sa.String(length=50), nullable=True))
    op.add_column('client_automobile', sa.Column('vehicle_model', sa.String(length=50), nullable=True))
    op.add_column('client_automobile', sa.Column('vehicle_year', sa.Integer(), nullable=True))
    op.add_column('client_automobile', sa.Column('engine_capacity_cc', sa.Integer(), nullable=True))
    op.add_column('client_automobile', sa.Column('fuel_type', sa.String(length=50), nullable=True))
    op.add_column('client_automobile', sa.Column('vehicle_usage', sa.String(length=50), nullable=True))
    op.add_column('client_automobile', sa.Column('seat_count', sa.Integer(), nullable=True))
    op.add_column('client_automobile', sa.Column('chassis_number', sa.String(length=100), nullable=True))
    op.add_column('client_automobile', sa.Column('vehicle_color', sa.String(length=50), nullable=True))
    op.add_column('client_automobile', sa.Column('country_of_registration', sa.String(length=100), nullable=True))
    op.add_column('client_automobile', sa.Column('driver_name', sa.String(length=100), nullable=True))
    op.add_column('client_automobile', sa.Column('license_issue_date', sa.Date(), nullable=True))
    op.add_column('client_automobile', sa.Column('license_expiry_date', sa.Date(), nullable=True))
    op.add_column('client_automobile', sa.Column('license_category', sa.String(length=50), nullable=True))
    op.add_column('client_automobile', sa.Column('driving_experience_years', sa.Integer(), nullable=True))
    op.add_column('client_automobile', sa.Column('accident_count', sa.Integer(), nullable=True))
    op.add_column('client_automobile', sa.Column('claim_count', sa.Integer(), nullable=True))
    op.add_column('client_automobile', sa.Column('no_claim_bonus_status', sa.String(length=50), nullable=True))
    op.add_column('client_automobile', sa.Column('previous_insurer', sa.String(length=100), nullable=True))
    op.drop_column('client_automobile', 'vehicle_age')
    op.add_column('client_health', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('client_health', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('client_health', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('client_health', sa.Column('smoking_status', sa.String(length=50), nullable=True))
    op.add_column('client_health', sa.Column('alcohol_consumption', sa.String(length=50), nullable=True))
    op.add_column('client_health', sa.Column('chronic_diseases', sa.Text(), nullable=True))
    op.add_column('client_health', sa.Column('past_surgeries', sa.Text(), nullable=True))
    op.add_column('client_health', sa.Column('current_medications', sa.Text(), nullable=True))
    op.add_column('client_health', sa.Column('family_medical_history', sa.Text(), nullable=True))
    op.add_column('client_health', sa.Column('coverage_type', sa.String(length=50), nullable=True))
    op.add_column('client_health', sa.Column('dependents_list', sa.Text(), nullable=True))
    op.add_column('client_health', sa.Column('maternity_coverage', sa.Boolean(), nullable=True))
    op.add_column('client_health', sa.Column('dental_optical_coverage', sa.Boolean(), nullable=True))
    op.alter_column('client_health', 'pre_existing_conditions',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('client_housing', sa.Column('property_type', sa.String(length=50), nullable=True))
    op.add_column('client_housing', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('client_housing', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('client_housing', sa.Column('property_size_sqm', sa.Float(), nullable=True))
    op.add_column('client_housing', sa.Column('room_count', sa.Integer(), nullable=True))
    op.add_column('client_housing', sa.Column('floor_count', sa.Integer(), nullable=True))
    op.add_column('client_housing', sa.Column('building_material', sa.String(length=100), nullable=True))
    op.add_column('client_housing', sa.Column('occupancy_type', sa.String(length=50), nullable=True))
    op.add_column('client_housing', sa.Column('building_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('client_housing', sa.Column('contents_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('client_housing', sa.Column('security_system', sa.Boolean(), nullable=True))
    op.add_column('client_housing', sa.Column('fire_protection', sa.Boolean(), nullable=True))
    op.add_column('client_housing', sa.Column('flood_zone', sa.Boolean(), nullable=True))
    op.add_column('client_housing', sa.Column('earthquake_zone', sa.Boolean(), nullable=True))
    op.add_column('client_housing', sa.Column('ownership_status', sa.String(length=50), nullable=True))
    op.add_column('client_housing', sa.Column('mortgage_info', sa.String(length=255), nullable=True))
    op.drop_column('client_housing', 'property_value')
    op.add_column('client_life', sa.Column('dependent_count', sa.Integer(), nullable=True))
    op.add_column('client_life', sa.Column('annual_income', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('client_life', sa.Column('source_of_income', sa.String(length=100), nullable=True))
    op.add_column('client_life', sa.Column('alcohol_consumption', sa.String(length=50), nullable=True))
    op.add_column('client_life', sa.Column('high_risk_activities', sa.Text(), nullable=True))
    op.add_column('client_life', sa.Column('medical_history_summary', sa.Text(), nullable=True))
    op.alter_column('client_life', 'beneficiaries',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('clients', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('id_expiry_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('employer_name', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('employment_status', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('annual_income', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('clients', sa.Column('kyc_status', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('pep_status', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('consent_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'consent_accepted')
    op.drop_column('clients', 'pep_status')
    op.drop_column('clients', 'kyc_status')
    op.drop_column('clients', 'annual_income')
    op.drop_column('clients', 'employment_status')
    op.drop_column('clients', 'employer_name')
    op.drop_column('clients', 'occupation')
    op.drop_column('clients', 'marital_status')
    op.drop_column('clients', 'id_expiry_date')
    op.drop_column('clients', 'nationality')
    op.alter_column('client_life', 'beneficiaries',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('client_life', 'medical_history_summary')
    op.drop_column('client_life', 'high_risk_activities')
    op.drop_column('client_life', 'alcohol_consumption')
    op.drop_column('client_life', 'source_of_income')
    op.drop_column('client_life', 'annual_income')
    op.drop_column('client_life', 'dependent_count')
    op.add_column('client_housing', sa.Column('property_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_column('client_housing', 'mortgage_info')
    op.drop_column('client_housing', 'ownership_status')
    op.drop_column('client_housing', 'earthquake_zone')
    op.drop_column('client_housing', 'flood_zone')
    op.drop_column('client_housing', 'fire_protection')
    op.drop_column('client_housing', 'security_system')
    op.drop_column('client_housing', 'contents_value')
    op.drop_column('client_housing', 'building_value')
    op.drop_column('client_housing', 'occupancy_type')
    op.drop_column('client_housing', 'building_material')
    op.drop_column('client_housing', 'floor_count')
    op.drop_column('client_housing', 'room_count')
    op.drop_column('client_housing', 'property_size_sqm')
    op.drop_column('client_housing', 'country')
    op.drop_column('client_housing', 'city')
    op.drop_column('client_housing', 'property_type')
    op.alter_column('client_health', 'pre_existing_conditions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('client_health', 'dental_optical_coverage')
    op.drop_column('client_health', 'maternity_coverage')
    op.drop_column('client_health', 'dependents_list')
    op.drop_column('client_health', 'coverage_type')
    op.drop_column('client_health', 'family_medical_history')
    op.drop_column('client_health', 'current_medications')
    op.drop_column('client_health', 'past_surgeries')
    op.drop_column('client_health', 'chronic_diseases')
    op.drop_column('client_health', 'alcohol_consumption')
    op.drop_column('client_health', 'smoking_status')
    op.drop_column('client_health', 'bmi')
    op.drop_column('client_health', 'weight_kg')
    op.drop_column('client_health', 'height_cm')
    op.add_column('client_automobile', sa.Column('vehicle_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('client_automobile', 'previous_insurer')
    op.drop_column('client_automobile', 'no_claim_bonus_status')
    op.drop_column('client_automobile', 'claim_count')
    op.drop_column('client_automobile', 'accident_count')
    op.drop_column('client_automobile', 'driving_experience_years')
    op.drop_column('client_automobile', 'license_category')
    op.drop_column('client_automobile', 'license_expiry_date')
    op.drop_column('client_automobile', 'license_issue_date')
    op.drop_column('client_automobile', 'driver_name')
    op.drop_column('client_automobile', 'country_of_registration')
    op.drop_column('client_automobile', 'vehicle_color')
    op.drop_column('client_automobile', 'chassis_number')
    op.drop_column('client_automobile', 'seat_count')
    op.drop_column('client_automobile', 'vehicle_usage')
    op.drop_column('client_automobile', 'fuel_type')
    op.drop_column('client_automobile', 'engine_capacity_cc')
    op.drop_column('client_automobile', 'vehicle_year')
    op.drop_column('client_automobile', 'vehicle_model')
    op.drop_column('client_automobile', 'vehicle_make')
    op.create_table('client_travel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('passport_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('frequent_destinations', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_travel_client_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_travel_pkey')),
    sa.UniqueConstraint('client_id', name=op.f('client_travel_client_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
