"""add financial fields to inter_company_shares

Revision ID: 34613cc19cbe
Revises: 275b3fe61a60
Create Date: 2025-12-21 02:33:36.607352+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34613cc19cbe'
down_revision = '275b3fe61a60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'ai_plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'CREDIT'::character varying"))
    op.alter_column('companies', 'ai_api_key_encrypted',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('inter_company_shares', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('inter_company_shares', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inter_company_shares', 'currency')
    op.drop_column('inter_company_shares', 'amount')
    op.alter_column('companies', 'ai_api_key_encrypted',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('companies', 'ai_plan',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'CREDIT'::character varying"))
    # ### end Alembic commands ###
