"""Add IBAN and SWIFT to EmployeeProfile

Revision ID: 4245204d218b
Revises: 526b52f8bbc5
Create Date: 2025-12-21 05:47:45.391984+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4245204d218b'
down_revision = '526b52f8bbc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('iban', sa.String(length=50), nullable=True))
    op.add_column('employee_profiles', sa.Column('swift_bic', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'swift_bic')
    op.drop_column('employee_profiles', 'iban')
    # ### end Alembic commands ###
