"""Fix missing co_insurance table

Revision ID: 440737129994
Revises: 4fdd8464460a
Create Date: 2025-12-21 04:03:03.287494+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440737129994'
down_revision = '4fdd8464460a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
