"""Add POS models

Revision ID: 4fdd8464460a
Revises: 06102bc43783
Create Date: 2025-12-21 03:57:24.101706+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdd8464460a'
down_revision = '06102bc43783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pos_location_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pos_location_id'], ['pos_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('policies', sa.Column('pos_location_id', sa.UUID(), nullable=True))
    op.add_column('policies', sa.Column('sale_channel', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'policies', 'pos_locations', ['pos_location_id'], ['id'])
    op.add_column('quotes', sa.Column('pos_location_id', sa.UUID(), nullable=True))
    op.add_column('quotes', sa.Column('sale_channel', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'quotes', 'pos_locations', ['pos_location_id'], ['id'])
    op.add_column('users', sa.Column('pos_location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'pos_locations', ['pos_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pos_location_id')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'sale_channel')
    op.drop_column('quotes', 'pos_location_id')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'sale_channel')
    op.drop_column('policies', 'pos_location_id')
    op.drop_table('commissions')
    op.drop_table('pos_inventory')
    op.drop_table('pos_locations')
    # ### end Alembic commands ###
