"""Add_payroll_columns

Revision ID: 60cd61a0ddd2
Revises: cf0276ea33c7
Create Date: 2025-12-22 18:27:00.155649+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cd61a0ddd2'
down_revision = 'cf0276ea33c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_transactions', sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('transport_allowance', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('housing_allowance', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('commissions_total', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('tax_is', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('tax_cn', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('tax_igr', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('social_security_cnps', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('payroll_transactions', sa.Column('net_pay', sa.Numeric(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_transactions', 'net_pay')
    op.drop_column('payroll_transactions', 'social_security_cnps')
    op.drop_column('payroll_transactions', 'tax_igr')
    op.drop_column('payroll_transactions', 'tax_cn')
    op.drop_column('payroll_transactions', 'tax_is')
    op.drop_column('payroll_transactions', 'commissions_total')
    op.drop_column('payroll_transactions', 'housing_allowance')
    op.drop_column('payroll_transactions', 'transport_allowance')
    op.drop_column('payroll_transactions', 'base_salary')
    # ### end Alembic commands ###
