"""Add notes to inter_company_shares

Revision ID: 78101427ef8c
Revises: c4e9fa67ca9a
Create Date: 2025-12-18 18:00:12.771727+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78101427ef8c'
down_revision = 'c4e9fa67ca9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inter_company_shares', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inter_company_shares', 'notes')
    # ### end Alembic commands ###
