"""Add co-insurance table

Revision ID: c4e9fa67ca9a
Revises: 2a048e2e16d7
Create Date: 2025-12-18 17:53:41.192836+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e9fa67ca9a'
down_revision = '2a048e2e16d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co_insurance_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('share_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'inter_company_shares', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inter_company_shares', 'clients', ['to_client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inter_company_shares', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inter_company_shares', type_='foreignkey')
    op.drop_constraint(None, 'inter_company_shares', type_='foreignkey')
    op.drop_constraint(None, 'inter_company_shares', type_='foreignkey')
    op.drop_table('co_insurance_shares')
    # ### end Alembic commands ###
