"""Add profile_picture to clients

Revision ID: cf0276ea33c7
Revises: 41ff599421ea
Create Date: 2025-12-21 07:39:11.246429+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0276ea33c7'
down_revision = '41ff599421ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'profile_picture')
    # ### end Alembic commands ###
